prague/ExternalAPICall:
  url: "/api/v1/norris"
  policy: "prague/ExternalAPICall"
  httpMethods:
  - "GET"
  properties: {}
  wssProcessingEnabled: false
prague/PragueCounterAPI:
  url: "/api/v1/counter"
  policy: "prague/PragueCounterAPI"
  httpMethods:
  - "DELETE"
  - "POST"
  - "GET"
  - "PUT"
  properties: {}
  wssProcessingEnabled: false
