usergroup/Test:
  url: "/api/v1/test"
  policy: "usergroup/Test"
  httpMethods:
  - "DELETE"
  - "POST"
  - "GET"
  - "PUT"
  properties: {}
  wssProcessingEnabled: false
usergroup/PragueCounterAPI:
  url: "/api/v1/counter"
  policy: "usergroup/PragueCounterAPI"
  httpMethods:
  - "DELETE"
  - "POST"
  - "GET"
  - "PUT"
  properties: {}
  wssProcessingEnabled: false
usergroup/ExternalAPICall:
  url: "/api/v1/norris"
  policy: "usergroup/ExternalAPICall"
  httpMethods:
  - "GET"
  properties: {}
  wssProcessingEnabled: false
usergroup/Jenkins Build Number:
  url: "/api/v1/jenkins/buildinfo"
  policy: "usergroup/Jenkins Build Number"
  httpMethods:
  - "DELETE"
  - "POST"
  - "GET"
  - "PUT"
  properties: {}
  wssProcessingEnabled: false
usergroup/JenkinsBuildNumber:
  url: "/api/v1/jenkins/buildinfo"
  policy: "usergroup/JenkinsBuildNumber"
  httpMethods:
  - "DELETE"
  - "POST"
  - "GET"
  - "PUT"
  properties: {}
  wssProcessingEnabled: false
usergroup/CounterAPI:
  url: "/api/v1/counter"
  policy: "usergroup/CounterAPI"
  httpMethods:
  - "DELETE"
  - "POST"
  - "GET"
  - "PUT"
  properties: {}
  wssProcessingEnabled: false
