ephemeral-gateway-test-pipelinemetrics:
  interfaceName: "com.l7tech.external.assertions.pbsmel.server.ServiceMetricsProcessor"
  operations:
  - policy: "metrics/influxdb"
    operationName: "process"
